services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tga
      POSTGRES_PASSWORD: tga_local
      POSTGRES_DB: trailgliders
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
